import {
  avatar1,
  avatar2,
  avatar3,
  avatar4,
  avatar5,
  avatar6,
  avatar7,
  avatar8,
  avatar9,
  avatar10,
  avatar11,
  avatar12,
  avatar13,
  avatar14,
  avatar15,
  avatar16,
  avatar17,
  image19,
  image20,
  image21,
  image13,
  image22,
  image16,
  image7,
  image33,
  image24,
  image25,
  image9,
  image26,
  image1,
  image2,
  image3,
  image4,
  image5,
  image6,
  image8,
  image10,
  image11,
  image12,
  image14,
  image15,
  image17,
  image18,
  art,
  paintbrush,
  collectible,
  swatches,
  musicNote,
  music,
  camera,
  photoGraphy,
  video,
  videoCamera,
  magicWand,
  utility,
  sport,
  basketBall,
  planet,
  virtualWorld,
} from '../assets';

const creators = [
  {
    name: 'Jaydon Ekstrom Bothman',
    img: avatar1,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Ruben Carder',
    img: avatar2,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Alfredo Septimus',
    img: avatar3,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Davis Franci',
    img: avatar4,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Livia Rosser',
    img: avatar5,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Kianna Donin',
    img: avatar6,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Phillip Lipshutz',
    img: avatar7,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Maria Rosser',
    img: avatar8,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Kianna Stanton',
    img: avatar9,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Angel Lubin',
    img: avatar10,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Allison Torff',
    img: avatar11,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Davis Workman',
    img: avatar12,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Lindsey Lipshutz',
    img: avatar13,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Randy Carder',
    img: avatar14,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Lydia Culhane',
    img: avatar15,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Rayna Bator',
    img: avatar16,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Jocelyn Westervelt',
    img: avatar17,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Marilyn Torff',
    img: avatar1,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Skylar Levin',
    img: avatar10,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
  {
    name: 'Terry Dorwart',
    img: avatar3,
    change: '+1.41%',
    sales: 602,
    volume: 12.4,
  },
];

const navLinks = [
  {
    id: 'marketplace',
    title: 'Marketplace',
  },
  {
    id: 'ranking',
    title: 'Ranking',
  },
  {
    id: 'connectwallet',
    title: 'Connect a wallet',
  },
];

const products = [
  {
    title: 'Magic Mushroom 0325',
    img: image19,
    price: 1.63,
    bid: 0.33,
    author: {
      name: 'Shroomie',
      img: avatar1,
    },
  },
  {
    title: 'Happy Robot 032',
    img: image20,
    price: 1.63,
    bid: 0.33,
    author: {
      name: 'BeKind2Robots',
      img: avatar2,
    },
  },
  {
    title: 'Happy Robot 024',
    img: image21,
    price: 1.63,
    bid: 0.33,
    author: {
      name: 'BeKind2Robots',
      img: avatar2,
    },
  },
  {
    title: 'Designer Bear',
    img: image13,
    price: 1.63,
    bid: 0.33,
    author: {
      name: 'Mr Fox',
      img: avatar3,
    },
  },
  {
    title: 'Colorful Dog 0356',
    img: image22,
    price: 1.63,
    bid: 0.33,
    author: {
      name: 'Keepitreal',
      img: avatar4,
    },
  },
  {
    title: 'Dancing Robot 0312',
    img: image16,
    price: 1.63,
    bid: 0.33,
    author: {
      name: 'Robotica',
      img: avatar5,
    },
  },
  {
    title: 'Cherry Blossom Girl 035',
    img: image7,
    price: 1.63,
    bid: 0.33,
    author: {
      name: 'MoonDancer',
      img: avatar6,
    },
  },
  {
    title: 'Space Travel',
    img: image33,
    price: 1.63,
    bid: 0.33,
    author: {
      name: 'NebulaKid',
      img: avatar7,
    },
  },
  {
    title: 'Sunset Dimension',
    img: image24,
    price: 1.63,
    bid: 0.33,
    author: {
      name: 'Animakid',
      img: avatar8,
    },
  },
  {
    title: 'Desert Walk',
    img: image25,
    price: 1.63,
    bid: 0.33,
    author: {
      name: 'Catch 22',
      img: avatar9,
    },
  },
  {
    title: 'IceCream Ape 0324',
    img: image9,
    price: 1.63,
    bid: 0.33,
    author: {
      name: 'Ice Ape Club',
      img: avatar10,
    },
  },
  {
    title: 'Colorful Dog 0344',
    img: image26,
    price: 1.63,
    bid: 0.33,
    author: {
      name: 'PuppyPower',
      img: avatar11,
    },
  },
];

const collections = [
  {
    title: 'DSGN Animals',
    creator: 'Jaydon Ekstrom Bothman',
    avatar: avatar1,
    products: [
      {
        title: 'Colorful Dog 0356',
        img: image22,
        price: 1.63,
        bid: 0.33,
      },
      {
        title: 'Colorful Dog 0344',
        img: image26,
        price: 1.63,
        bid: 0.33,
      },
      {
        title: 'Designer Bear',
        img: image13,
        price: 1.63,
        bid: 0.33,
      },
    ],
  },
  {
    title: 'DSGN Animals',
    creator: 'Jaydon Ekstrom Bothman',
    avatar: avatar1,
    products: [
      {
        title: 'Colorful Dog 0356',
        img: image22,
        price: 1.63,
        bid: 0.33,
      },
      {
        title: 'Colorful Dog 0344',
        img: image26,
        price: 1.63,
        bid: 0.33,
      },
      {
        title: 'Designer Bear',
        img: image13,
        price: 1.63,
        bid: 0.33,
      },
    ],
  },
  {
    title: 'DSGN Animals',
    creator: 'Jaydon Ekstrom Bothman',
    avatar: avatar1,
    products: [
      {
        title: 'Colorful Dog 0356',
        img: image22,
        price: 1.63,
        bid: 0.33,
      },
      {
        title: 'Colorful Dog 0344',
        img: image26,
        price: 1.63,
        bid: 0.33,
      },
      {
        title: 'Designer Bear',
        img: image13,
        price: 1.63,
        bid: 0.33,
      },
    ],
  },
];

const categories = [
  {
    title: 'art',
    img: art,
    icon: paintbrush,
  },
  {
    title: 'collectibles',
    img: collectible,
    icon: swatches,
  },
  {
    title: 'music',
    img: music,
    icon: musicNote,
  },
  {
    title: 'photography',
    img: photoGraphy,
    icon: camera,
  },
  {
    title: 'video',
    img: video,
    icon: videoCamera,
  },
  {
    title: 'utility',
    img: utility,
    icon: magicWand,
  },
  {
    title: 'sport',
    img: sport,
    icon: basketBall,
  },
  {
    title: 'virtual world',
    img: virtualWorld,
    icon: planet,
  },
];
export { creators, navLinks, products, collections, categories };
